version: "3.7"
services:
  server:
    image: "backend-deploy-test/backend-deploy-test-server:latest"
    platform: linux/arm64
    build: .
    container_name: backend-for-aws-deploy-test
    restart: unless-stopped
    volumes:
      - appdata:/app
    ports:
      - "7777:7777"
    command:
      - bash
      - -c
      - |
        java -jar /app.jar
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  appdata:
    driver: local
