version: "3.7"
services:
  server:
    platform: linux/arm64
    container_name: backend-for-aws-deploy-test
    image: silenc3502/backend-deploy-test-server
    expose:
      - 7777
    ports:
      - 7777:7777
