name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Create application.yaml for CI Test
      run: |
        mkdir -p src/main/resources
        cd src/main/resources
        pwd
        echo "${{ secrets.CI_TEST_CONFIG }}" > application.properties
        cat application.properties
        
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8' 
        mysql database: 'jpa_test' 
        mysql user: 'eddi'
        mysql password: ${{ secrets.MYSQL_PASSWORD }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Test with Gradle
      run: |
        cat src/main/resources/application.properties
        ./gradlew test

    - name: send TEST_FINISH_TRIGGER
      run: |
        curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -u ${{ secrets.GHCR_TOKEN }} \
            -d '{"event_type": "TEST_FINISH_TRIGGER", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}' 
