name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'deploy_test'
          mysql user: 'eddi'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Project with Gradle
        run: ./gradlew --stacktrace clean build -x test
        
      - name: Test with Gradle
        run: ./gradlew test
